$Statement = "insert into TemplatesArchive
(Archived,guid,cn,distinguishedName,flags,msPKICertificateApplicationPolicy,msPKICertificateNameFlag,msPKICertificatePolicy,
msPKICertTemplateOID,msPKIEnrollmentFlag,msPKIMinimalKeySize,msPKIPrivateKeyFlag,msPKIRAApplicationPolicies,msPKIRAPolicies,
msPKIRASignature,msPKISupersedeTemplates,msPKITemplateMinorRevision,msPKITemplateSchemaVersion,pKICriticalExtensions,pKIDefaultCSPs,
pKIDefaultKeySpec,pKIExpirationPeriod,pKIExtendedKeyUsage,pKIKeyUsage,pKIMaxIssuingDepth,pKIOverlapPeriod,ntSecurityDescriptor) 
select CURRENT_TIMESTAMP,guid,cn,distinguishedName,flags,msPKICertificateApplicationPolicy,msPKICertificateNameFlag,msPKICertificatePolicy,
msPKICertTemplateOID,msPKIEnrollmentFlag,msPKIMinimalKeySize,msPKIPrivateKeyFlag,msPKIRAApplicationPolicies,msPKIRAPolicies,msPKIRASignature,
msPKISupersedeTemplates,msPKITemplateMinorRevision,msPKITemplateSchemaVersion,pKICriticalExtensions,pKIDefaultCSPs,pKIDefaultKeySpec,
pKIExpirationPeriod,pKIExtendedKeyUsage,pKIKeyUsage,pKIMaxIssuingDepth,pKIOverlapPeriod,ntSecurityDescriptor 
from templates where GUID = '{0}'" -f $GUID