// <auto-generated />
using System;
using CertificateManager.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CertificateManager.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260304071224_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CertificateManager.Models.CRL", b =>
                {
                    b.Property<int>("CRLRowId")
                        .HasColumnType("int");

                    b.Property<string>("CAConfig")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("CRLNextPublish")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("CRLNextUpdate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CRLNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CRLRawCRL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CRLThisUpdate")
                        .HasColumnType("datetime2");

                    b.HasKey("CRLRowId", "CAConfig");

                    b.ToTable("CRL");
                });

            modelBuilder.Entity("CertificateManager.Models.EKU", b =>
                {
                    b.Property<int>("SANId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SANId"));

                    b.Property<string>("CAConfig")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RequestId")
                        .HasColumnType("int");

                    b.HasKey("SANId");

                    b.HasIndex("RequestId", "CAConfig");

                    b.ToTable("EKU");
                });

            modelBuilder.Entity("CertificateManager.Models.Entry", b =>
                {
                    b.Property<int>("RequestId")
                        .HasColumnType("int");

                    b.Property<string>("CAConfig")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Base64Certificate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Base64Request")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CallerName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CertificateEffectiveDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("CertificateExpirationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CertificateHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CertificateTemplate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IssuedCommonName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IssuedCountryRegion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IssuedEmailAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IssuedOrganization")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IssuedOrganizationUnit")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Monitoring")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Owner")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PublicKeyAlgorithm")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PublicKeyAlgorithmParameters")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PublicKeyLength")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RequestAttributes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RequestCity")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RequestCommonName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RequestCountryRegion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RequestDisposition")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RequestEmailAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RequestOrganization")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RequestOrganizationUnit")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RequestTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RequestType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RequesterName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("RevocationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("RevocationReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SerialNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Successor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TemplateEnrollmentFlags")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TemplateGeneralFlags")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TemplatePrivateKeyFlags")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RequestId", "CAConfig");

                    b.ToTable("Entry");
                });

            modelBuilder.Entity("CertificateManager.Models.RevokedCert", b =>
                {
                    b.Property<int>("RevokedCertId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RevokedCertId"));

                    b.Property<string>("CAConfig")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("CRLRowId")
                        .HasColumnType("int");

                    b.Property<string>("Reason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("RevocationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("SerialNumber")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RevokedCertId");

                    b.HasIndex("CRLRowId", "CAConfig");

                    b.ToTable("RevokedCert");
                });

            modelBuilder.Entity("CertificateManager.Models.SAN", b =>
                {
                    b.Property<int>("SANId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SANId"));

                    b.Property<string>("CAConfig")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("RequestId")
                        .HasColumnType("int");

                    b.Property<string>("SubjectAlternativeName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SANId");

                    b.HasIndex("RequestId", "CAConfig");

                    b.ToTable("SAN");
                });

            modelBuilder.Entity("CertificateManager.Models.Template", b =>
                {
                    b.Property<string>("GUID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CN")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DistinguishedName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("flags")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("msPKICertTemplateOID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("msPKICertificateApplicationPolicy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("msPKICertificateNameFlag")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("msPKICertificatePolicy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("msPKIEnrollmentFlag")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("msPKIMinimalKeySize")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("msPKIPrivateKeyFlag")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("msPKIRAApplicationPolicies")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("msPKIRAPolicies")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("msPKIRASignature")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("msPKISupersedeTemplates")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("msPKITemplateMinorRevision")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("msPKITemplateSchemaVersion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ntSecurityDescriptor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("pKICriticalExtensions")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("pKIDefaultCSPs")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("pKIDefaultKeySpec")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("pKIExpirationPeriod")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("pKIExtendedKeyUsage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("pKIKeyUsage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("pKIMaxIssuingDepth")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("pKIOverlapPeriod")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("GUID");

                    b.ToTable("Template");
                });

            modelBuilder.Entity("CertificateManager.Models.TemplateArchive", b =>
                {
                    b.Property<string>("GUID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CN")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DistinguishedName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("flags")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("msPKICertTemplateOID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("msPKICertificateApplicationPolicy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("msPKICertificateNameFlag")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("msPKICertificatePolicy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("msPKIEnrollmentFlag")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("msPKIMinimalKeySize")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("msPKIPrivateKeyFlag")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("msPKIRAApplicationPolicies")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("msPKIRAPolicies")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("msPKIRASignature")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("msPKISupersedeTemplates")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("msPKITemplateMinorRevision")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("msPKITemplateSchemaVersion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ntSecurityDescriptor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("pKICriticalExtensions")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("pKIDefaultCSPs")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("pKIDefaultKeySpec")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("pKIExpirationPeriod")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("pKIExtendedKeyUsage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("pKIKeyUsage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("pKIMaxIssuingDepth")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("pKIOverlapPeriod")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("GUID");

                    b.ToTable("TemplatesArchiv");
                });

            modelBuilder.Entity("CertificateManager.Models.EKU", b =>
                {
                    b.HasOne("CertificateManager.Models.Entry", "Entry")
                        .WithMany("EKU")
                        .HasForeignKey("RequestId", "CAConfig")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Entry");
                });

            modelBuilder.Entity("CertificateManager.Models.RevokedCert", b =>
                {
                    b.HasOne("CertificateManager.Models.CRL", "CRL")
                        .WithMany("RevokedCert")
                        .HasForeignKey("CRLRowId", "CAConfig")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CRL");
                });

            modelBuilder.Entity("CertificateManager.Models.SAN", b =>
                {
                    b.HasOne("CertificateManager.Models.Entry", "Entry")
                        .WithMany("SAN")
                        .HasForeignKey("RequestId", "CAConfig")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Entry");
                });

            modelBuilder.Entity("CertificateManager.Models.CRL", b =>
                {
                    b.Navigation("RevokedCert");
                });

            modelBuilder.Entity("CertificateManager.Models.Entry", b =>
                {
                    b.Navigation("EKU");

                    b.Navigation("SAN");
                });
#pragma warning restore 612, 618
        }
    }
}
